# Generated by Django 5.2 on 2025-05-18 17:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_account_customer', models.BooleanField(default=False)),
                ('xero_contact_id', models.CharField(max_length=255, unique=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('xero_last_modified', models.DateTimeField(null=True)),
                ('xero_last_synced', models.DateTimeField(null=True)),
                ('django_created_at', models.DateTimeField(auto_now_add=True)),
                ('django_updated_at', models.DateTimeField(auto_now=True)),
                ('xero_tenant_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'workflow_client',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('xero_contact_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_supplier',
            },
        ),
    ]
