# Generated by Django 5.2 on 2025-05-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
    ]
