# This file is autogenerated by update_init.py script

from .client_view import ClientListView, ClientUpdateView, UnusedClientsView

__all__ = [
    'ClientListView',
    'ClientUpdateView',
    'UnusedClientsView',
]
