# Generated by Django 5.2 on 2025-06-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('job', '0002_alter_historicaljob_pricing_type_and_more'),
        ('workflow', '0147_companydefaults_po_prefix'),
    ]
    
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Client',
                ),
                migrations.CreateModel(
                    name='Client',
                    fields=[],
                    options={
                        'proxy': True,
                        'indexes': [],
                        'constraints': [],
                    },
                    bases=('clients.client',),
                ),
            ],
        ),
    ]
